// Generated by: npx supabase gen types typescript --local > lib/supabase/database.types.ts
// Run this command after executing Supabase migrations to get full type safety

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          avatar_url: string | null;
          notify_leaderboard: boolean;
          notify_badges: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          avatar_url?: string | null;
          notify_leaderboard?: boolean;
          notify_badges?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          avatar_url?: string | null;
          notify_leaderboard?: boolean;
          notify_badges?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      levels: {
        Row: {
          id: number;
          name: string;
          theme: string;
          description: string | null;
          order_index: number;
          is_active: boolean;
        };
        Insert: {
          id: number;
          name: string;
          theme: string;
          description?: string | null;
          order_index: number;
          is_active?: boolean;
        };
        Update: {
          id?: number;
          name?: string;
          theme?: string;
          description?: string | null;
          order_index?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      scores: {
        Row: {
          id: string;
          user_id: string;
          level_id: number;
          score: number;
          time_seconds: number;
          quiz_bonus: number;
          completed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          level_id: number;
          score: number;
          time_seconds: number;
          quiz_bonus?: number;
          completed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          level_id?: number;
          score?: number;
          time_seconds?: number;
          quiz_bonus?: number;
          completed_at?: string;
        };
        Relationships: [];
      };
      badges: {
        Row: {
          id: string;
          name: string;
          description: string;
          icon_url: string;
          condition_type: string;
          condition_value: Json;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          icon_url: string;
          condition_type: string;
          condition_value?: Json;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          icon_url?: string;
          condition_type?: string;
          condition_value?: Json;
        };
        Relationships: [];
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_id: string;
          earned_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          badge_id: string;
          earned_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          badge_id?: string;
          earned_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      leaderboard_view: {
        Row: {
          user_id: string;
          username: string;
          avatar_url: string | null;
          total_score: number;
          levels_completed: number;
          rank: number;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
